resources:
  - name: pipelines
    icon: github
    type: git
    source:
      uri: https://github.com/SapphicCode/ci-pipelines.git

jobs:
  - name: self
    serial: yes
    plan:
      - get: pipelines
        trigger: yes
      - set_pipeline: self
        file: pipelines/pipeline.yml

  - name: z-vaultui
    serial: yes
    plan:
      - get: pipelines
        trigger: yes
      - set_pipeline: vaultui
        team: purringchaos
        file: pipelines/z/vaultui/pipeline.yml
