resources:
  - name: vaultui
    icon: github
    type: git
    source:
      uri: https://github.com/purringChaos/VaultUI.git

jobs:
  - name: build
    public: yes
    serial: yes
    plan:
      - get: vaultui
        trigger: yes

      - task: build
        config: &node
          inputs:
            - name: vaultui
              path: .
          outputs:
            - name: dist
          caches:
            - path: node_modules

          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker.io/library/node
              tag: lts

          run:
            path: bash
            args:
              - -exc
              - |
                npm install
                npx webpack
      - task: deploy
        config:
          inputs:
            - name: dist

          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker.io/rclone/rclone

          params:
            RCLONE_CONFIG_B2_TYPE: b2
            RCLONE_CONFIG_B2_ACCOUNT: (("../phoenix/b2".account))
            RCLONE_CONFIG_B2_KEY: (("../phoenix/b2".key))
          run:
            path: rclone
            args:
              - sync
              - -v
              - ./dist
              - b2:Cassandra-Friends/Z/vaultui
